#!/bin/sh -e

PACKAGE_NAME=multitouch
CVERSION=`dpkg-query -W -f='${Version}' ${PACKAGE_NAME}-kernel-source | awk -F "-" '{print $1}' | cut -d\: -f2`
ARCH=`dpkg --print-architecture`
#DEBHELPER#

case "$1" in
	configure)
	# Build the kernel module
	/usr/lib/dkms/common.postinst $PACKAGE_NAME $CVERSION /usr/share/$PACKAGE_NAME $ARCH $2

	# Update initramfs
	update-initramfs -u
	;;
esac

#DEBHELPER#
